provider: 
  - name: Netlify
    profile: my-netlify-credential
    domains:
      - name: example.tk
        records:
          - name: "@"
            value: 1.2.3.4
            type: IPv4
          - name: pgadmin
            value: test
            type: TXT
  - name: Cloudflare
    profile: my-cloudflare-credential
    domains:
      - name: example.tk
        records:
          - name: "@"
            value: 1.2.3.4
            type: IPv4
          - name: pgadmin
            value: test
            type: TXT    