name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-cross-platform:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: List all OS & Architectures supported by Go
        run: go tool dist list

      - name: Build
        run: bash ./build.sh
  
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repo
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: snapcore/action-build@v1
        with:
          path: ./snap
          # snapcraft-args: --use-lxd
